Support for load/stores for pointer types in worker-interp
yotann/alive2 pull request #2
Opened 2021-10-27 16:03 UTC by nbushehri

Also updated the some of the previous tests that included values larger than 255 for value bytes in memory

2021-10-28 16:59 UTC, yotann requested changes

2021-10-28 16:59 UTC, yotann commented on ir/instr.cpp
> +static void storePtrVal(Interpreter &interpreter, util::ConcreteValPointer *ptr_dst,
This function needs to store every byte of the pointer and set `ConcreteByte::pointer_byte_offset` to a different value for each byte. Then we can detect UB in cases like:

- Storing an 8-byte pointer to a 1-byte memory block.
- Storing a pointer that overwrites part of an integer, and then loading the integer.
- Storing an integer that overwrites part of a pointer, and then loading the pointer.

The number of bytes in a pointer depends on target architecture, looks like the correct number is `bits_program_pointer / bits_byte`.

2021-10-28 16:59 UTC, yotann commented on ir/instr.cpp
> +static util::ConcreteVal *loadPtrVal(Interpreter &interpreter,
Likewise needs to load all bytes of the pointer, and check that they all belong to the same pointer and have correct values in `ConcreteByte::pointer_byte_offset`.

2021-10-28 16:59 UTC, yotann commented on ir/instr.cpp
> +        loadPtrVal(interpreter, c_ptr, getType().bits()));
`getType().bits()` is actually irrelevant for pointers. It's used for converting a pointer to a BV for the solver, but we aren't doing that, we're just storing the pointer directly in `ConcreteByte::ptr_val`.

2021-11-01 19:26 UTC, nbushehri commented
I think commit d6bb9aeeabd2720b70edf4d47729d6044e47d8e2 addresses the above issues.

2021-11-03 02:53 UTC, merged

2021-11-03 03:39 UTC, yotann commented
I figured out why some bytes were greater than 255; see #3. I made some changes after accepting:

- 25cfa63ff34daec9382b4416c8c889f7cf452c3a and ebaee10a53e773d69827a90ec9c5f54ae0732a18: see #3 
- efa9ef3d41313af96f6d99697f0d95080984fae2: you forgot one check of is_ub
- 6af8b6fd15b90853781c26f893f18b771986092e: I fixed some asserts/UB that should have been UB/unsupported.

I also merged the upstream changes from Alive2, so you should merge my branch before your next PR.